### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Leafy3311** [bossley9/minify-html#1]
This is the error message when I try to install:
Installing “https://github.com/bossley9/minify-html.git” failed. 
Couldn't clone https://github.com/bossley9/minify-html.git

**Comment by bossley9** [comment]
Apologies for such a late reply. It turns out that the package had issues uploading to Atom's package manager. 
Please try uninstalling the package, restarting Atom, and reinstalling the package.
The issue should now be fixed.

**Comment by Leafy3311** [comment]
Thanks it works now!
